spring:
  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://localhost:8083/api/auth
          predicates:
            - Path=/api/auth/**
          filters:
            - name: Logging
              args:
                baseMessage: My Custom Message
                authenticated: true
                postLogger: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
