spring:
  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://localhost:8083
          predicates:
            - Path=/api/auth/**
          filters:
            - name: Logging
              args:
                baseMessage: My Custom Message
                authenticated: false
                postLogger: true
        - id: gestionReclam
          uri: http://localhost:8085
          predicates:
            - Path=/gest/api/**
          filters:
            - StripPrefix=1
            - name: Logging
              args:
                baseMessage: Accessed Gest service
                authenticated: true
                postLogger: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
