spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.Oracle10gDialect
    database: oracle
server:
  port: 8081